### PR TITLE
Adds text to setup page

### PR DESCRIPTION
**Pull request by srappel**
Still some review to do, but I wanted to get some text in there.

### CODE REVIEW

**Comment by sstevens2** [comment]
Think it looks good but it is missing a few links.

**Comment by srappel** [comment]
> Think it looks good but it is missing a few links.

The missing links are for the main workshop website and the data download. Do we have URLs for those yet?

**Comment by sstevens2** [comment]
For the workshop website, maybe we should link this page? https://uw-madison-datascience.github.io/geospatial-workshop/. Then it is evergreen, instead of linked to a specific time we taught the lesson.
Data Download might have to wait until we have finalized the data folder, then we can zip it and add the zipped folder for download.  For this we can merge and then leave an issue to remind us to zip, upload, link.

**Comment by srappel** [comment]
>  For this we can merge and then leave an issue to remind us to zip, upload, link.

Okay, I can make this issue.

**Pull request merged**
