### PR TITLE
add deploy step

### PR DESCRIPTION
**Pull request by zkamvar**
I've added a deploy step that should push to changes to the `_episodes` folder once it gets merged into the gh-pages branch.

### CODE REVIEW

**Comment by zkamvar** [comment]
See this automated commit from my fork: https://github.com/zkamvar/geospatial-capstone/commit/5c13c9176e422e0a80ede5aebd7c3471cf908808?short_path=01b30d5#diff-01b30d545ebb59634b47f4004e8d870d2e13edc89a000618834124aff43da7b4

At the moment, figures are not showing up because they setup chunk needs to look something like this:

https://github.com/swcarpentry/r-novice-gapminder/blob/c922ea4abe6ceede7f0a08b1e9b04e88ea34e30b/_episodes_rmd/02-project-intro.Rmd#L17-L20

**Comment by sstevens2** [comment]
Thanks @zkamvar!  I'll merge this to get the deploy step added and then make sure we include that setup code chunk in the Rmds for this lesson.  Really appreciate your help on this!

**Comment by sstevens2** [comment]
I'm now seeing the push site and make lesson check fail. I know you said the lesson check is okay to fail.  I'm guessing I need the push site to work but not sure?

**Comment by zkamvar** [comment]
> I'm now seeing the push site and make lesson check fail. I know you said the lesson check is okay to fail. I'm guessing I need the push site to work but not sure?

If you look at the output of make lesson-check, it shows you all the FIXMEs that are still in your lesson for the most part, which are expected since this lesson is still being developed.

Merging this would indeed build the lesson on the _episodes/ folder in the default branch. The only thing you will want to watch out for is to make sure that people pull before they push and that they don't change anything in the _episodes/ folder.

**Pull request closed without merging**
